### ISSUE TITLE
Question: Is  kernel linux-rkbsp-joshua-git-6.1.25 Compatible With OPi5-Plus?

### ISSUE THREAD

**Issue by JFLim1** [7Ji/archrepo#23]
Hi,
Read with interest on  your new kernel linux-rkbsp-joshua-git-6.1.25.  Is this new kernel  linux-rkbsp-joshua-git-6.1.25 compatible/can be use on Orange Pi 5 Plus?

**Comment by 7Ji** [comment]
Yes, it's wyf9661's package and he created for and tested it on his 5 plus.

**Comment by 7Ji** [comment]
And please don't ask questions on possibility here. Only report breakage. 

This issues section is for packages you installed from here and the repo itself. 

Questions regarding the packge themselves should be opened under 7Ji-PKGBUILDs/.report.
