### ISSUE TITLE
Feedback: linux-rkbsp-joshua-git 6.1.43.r1266023.8372abb8befa-1 Wifi Not Available Or Stable on WIFI Module 8852BE

### ISSUE THREAD

**Issue by JFLim1** [7Ji/archrepo#25]
Device: Opi5-Plus
Wifi Module: 8852BE (So called Official Orange Pi 5 Plus Wifi Module)

On linux-rkbsp-joshua-git 6.1.43.r1266023.8372abb8befa-1 WIFI is not stable.  System will continue to try to activate the WIFI. Message "Wireless Interface  (wIP2p33s0). WiFi network cannot be found"  The firmware used did not seem to make a difference -- "linux-firmware-orangepi-git" or "linux-firmware-joshua-git".

On linux-rkbsp-6.1.43-2 NO WiFi connection at all.

**Comment by 7Ji** [comment]
Not a package issue, not a repo issue, a PKGBUILD issue goes to 7JI-PKGBUILDs/.report . And even you place it right, this is something I couldn't/ won't fix: that package sticks to the upstream and it delivers what upstream delivers.
