### ISSUE TITLE
chromium-mpp is missing

### ISSUE THREAD

**Issue by kwankiu** [7Ji/archrepo#26]
The package chromium-mpp is missing from your repo

**Comment by 7Ji** [comment]
```
> pacman -Ss '^chromium-mpp$'
7Ji/chromium-mpp 114.0.5735.198-4
    A web browser built for speed, simplicity, and security. Patched with Rockchip MPP support.
```

It was removed when a full update was triggered during the clang issue. But that's solved now. It's back in the repo.
