### ISSUE TITLE
packages in agrrepo

### ISSUE THREAD

**Issue by hbiyik** [7Ji/archrepo#33]
hello @7Ji 

i noticed that some packages in the builder are using agrrepo (ie: mesa-panfrost-git, mesa-panvk-git),

i can move those to 7jiPKGBUILDs organization if they are used,

i am randomly moving stuff in agrrepo since paths do not matter in agr but could be a pain for you to maintain it..

**Comment by 7Ji** [comment]
Thanks, I'd be happy for that.

**Comment by hbiyik** [comment]
closed due to https://github.com/7Ji-PKGBUILDs/.meta/issues/49
