### ISSUE TITLE
Getting kodi-mpp-git back to repo

### ISSUE THREAD

**Issue by kyak** [7Ji/archrepo#42]
Hi @7Ji 

Currently https://github.com/7Ji-PKGBUILDs/kodi-mpp-git builds just fine.

Please consider adding kodi-mpp-git back to the repo.

Thanks!

**Comment by 7Ji** [comment]
Closed by https://github.com/7Ji/archrepo/commit/a95d12f3841409ee58bd429a97539dfcd1441bfb

Sorry I'm very busy these days and just had time to re-enable it.
