### ISSUE TITLE
llvm-libs >= 16 update breaks mali-panfork-git

### ISSUE THREAD

**Issue by 7Ji** [7Ji/archrepo#6]
The library `libOSMesa.so` in the package links to `libLLVM-15.so`, which is now superceded by `libLLVM-16.so`

The package is now being rebuilt and a manual re-installation is needed once the new package is available to fix the problem.

**Comment by 7Ji** [comment]
@hbiyik  @ericwoud FYI

**Comment by hbiyik** [comment]
thanks for updating, it was asked in radxa forums as well.
