### ISSUE TITLE
Add 7Ji repo keyring package

### ISSUE THREAD

**Issue by SputnikRocket** [7Ji/archrepo#9]
For ease of installation by the user and ease of upgrading without manual intervention in case the key changes/updates

**Comment by 7Ji** [comment]
I've added the package in e2cd50aff6df79d7d0b7d3fd4da6ebfbde72ecf4 , and the package file should be uploaded after the earliest daily build. Close later after upload.

**Comment by SputnikRocket** [comment]
alright, thank you. I will
